export const mocktestAnswer = {
  1: ["Cat"],
  2: ["Dog"],
  3: ["Cat", "Dog"],
  4: ["Water"],
  5: ["Microwave"],
  6: ["Cat", "Dog"],
  7: ["Cat", "Dog"],
  8: ["Cat", "Dog"],
  9: ["Cat", "Dog"],
  10: ["Cat", "Dog"],
  11: ["Cat", "Dog"],
  12: ["Cat", "Dog"],
  13: ["Cat", "Dog"],
  14: ["Cat", "Dog"],
  15: ["Cat", "Dog"],
  16: ["Cat", "Dog"],
  17: ["Cat", "Dog"],
  18: ["Cat", "Dog"],
  19: ["Cat", "Dog"],
  20: ["Cat", "Dog"],
  21: ["Cat", "Dog"],
  22: ["Cat", "Dog"],
  23: ["Cat", "Dog"],
  24: ["Cat", "Dog"],
  25: ["Cat", "Dog"],
  26: ["Cat", "Dog"],
  27: ["Cat", "Dog"],
  28: ["Cat", "Dog"],
  29: ["Cat", "Dog"],
  30: ["Cat", "Dog"],
  31: ["Cat", "Dog"],
  32: ["Cat", "Dog"],
  33: ["Cat", "Dog"],
  34: ["Cat", "Dog"],
  35: ["Cat", "Dog"],
  36: ["Cat", "Dog"],
  37: ["Cat", "Dog"],
  38: ["Cat", "Dog"],
  39: ["Cat", "Dog"],
  40: ["Cat", "Dog"],
};
